# The URL the site will be built for
base_url = "nichirikyoukai.github.io"
title = "日利協会"
description = "الجمعية الليبية اليابانية"
author="الجمعية الليبية اليابانية"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Generates info for RSS readers
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "visual-studio-dark"

[extra]
# Put all your custom variables here'
lang = "ar"
dir = "rtl"
author = "نصف الحقوق محفوظة"
x_account = "lyjp_"

[extra.content]
index_title = "السلام عليكم!"
index_content = "«<span class='dark:text-blue-400 text-blue-600'>يا أيّها الناسُ إنا خلقناكم من ذكرٍ وأنثى وجعلناكم شعوبًا وقبائل لتعارفوا</span>».<br>هذه مبادرة لإشاعةِ الوُدِّ والتفاهم بين بلاد اليابان وليبيا، لتَكونَ سُلّمًا إلى تبادلِ المنافعِ بين القلوبِ والعقول، ليألفَ القوم بعضهم بعضًا، وتأنس النفوسُ إلى ما عند الآخر من فضلٍ وعلمٍ وصنائعَ جميلة."